### ISSUE TITLE
Do we want to add calendar information to the groups.io calendar we're using at OCA?

### ISSUE THREAD

**Issue by adammontville** [opencybersecurityalliance/PACE#15]
Groups.io is the host for our OCA mailing lists. `oca-pace-wg` is a subgroup of `oasis-open-projects`. We would like to see if we can make the PACE calendar publicly viewable, so that PACE WG participants do not need to create yet another login.

Before that, we need to determine if we can add the weekly PACE meeting to the calendar.

**Comment by adammontville** [comment]
As an option, we could always place the meeting information on the GitHub README page. There _is_ already a link to the meeting information sent to the mailing list.

**Comment by JasonKeirstead** [comment]
The calendars are public here https://lists.oasis-open-projects.org/g/oca-pace-wg/calendar

But, only members can subscribe??? This is confusing. @claurau maybe should look and see if a setting is misconfigured. I don't have the required access.

**Comment by dlemire60** [comment]
Two points:

1) On my previous visits to that page (via my bookmark for it), the calendar item at the left wasn't visible, so some magic has happened.
1) I have absolutely no idea what account would be associated with this page that I would use for logging in.

AKA: there's a need for greater information sharing about this tool.

**Comment by JasonKeirstead** [comment]
@claurau is out sick right now but when she returns she can probably organize a session for the OCA @dlemire60 . I agree it would be a good thing to do. As to the account - you create the account yourself, using the email address you used to subscribe to the mailing list. If you need your account reset, let us know. You do seem to have one, and you are marked as a moderator (is it saved in your web browser?) 

It is affiliated with your @hii-tsd.XXX email address.

**Comment by JasonKeirstead** [comment]
FYI I confirmed that anyone, logged in or not, can subscribe to the calendar with this "magic" URL

https://lists.oasis-open-projects.org/g/oca-pace-wg/ics/10901507/1485334643/feed.ics

**Comment by dlemire60** [comment]
> As to the account  ... You do seem to have one, and you are marked as a moderator (is it saved in your web browser?)

Thanks, Jason. I suspect that was created automatically when I was added to the mail list and I wasn’t aware. It’s now got a proper password and a place in my password manager. And the left menu options grow dramatically when you’re logged in.

As for being a moderator:  news to me.

**Comment by dlemire60** [comment]
> FYI I confirmed that anyone, logged in or not, can subscribe to the calendar with this "magic" URL

Can you clarify what "subscribe" means in this context?  Something like having it magically update my work calendar in Outlook?

**Comment by JasonKeirstead** [comment]
@dlemire60 If you subscribe to that ICS file using a program like Google Calendar or Outlook then it should stay up-to-date with all of the latest changes. If you do it as a one-time download and manual import, it would not.

**Comment by dlemire60** [comment]
@JasonKeirstead Got it, thanks. Tried it and can see your "test" event.
