### ISSUE TITLE
Do we want to record (and post) our meetings?

### ISSUE THREAD

**Issue by adammontville** [opencybersecurityalliance/PACE#16]
It was suggested that we record and post our weekly, and potentially other related, PACE meetings. It is easy enough to record the meetings. These are typically stored on WebEx, or they can be downloaded and posted elsewhere. Alternative locations would be preferable, and we could consider groups.io or this github repository.

**Comment by warrenrjwc** [comment]
I would suggest posting a recording and/or meeting notes as many folks cannot make the meeting time.
