### ISSUE TITLE
Which collaborative development model?

### ISSUE THREAD

**Issue by sparrell** [opencybersecurityalliance/PACE#17]
There are different models for using Pull Requests in GitHub.
See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/about-collaborative-development-models

We could choose either the fork and pull model or the shared repository model but I recommend the fork and pull model since we are an open group that hopes to grow beyond the few initial people.

**Comment by sparrell** [comment]
discussion at 10-Jan-2022 meeting reached consensus that we would use the fork and pull collaborative development model

**Comment by dlemire60** [comment]
Address in PR #21.
