### ISSUE TITLE
SACM considerations?

### ISSUE THREAD

**Issue by wmunyan** [opencybersecurityalliance/PACE#22]
Given that the SACM architecture draft has officially expired, and the SACM working group will be closed once its last remaining draft (CoSWID) is published, are there considerations within this group as to what is being instantiated?  Will the SACM architecture draft be pulled into this group?

**Comment by adammontville** [comment]
Hi Bill. 

I’m not sure that the draft will be pulled in explicitly, but (and others please correct me where I’m mistaken) we are working on an implementation that should inform any reincarnation of that draft.

Kind regards,

Adam

**Comment by dlemire60** [comment]
I think right now I would say that the SACM architecture ID is foundation / inspiration for the prototyping work to be done under OCA PACE. As the focus of  the PACE effort is prototyping, I don't have any near-term expectations that we'd update / revise / expand on the SACM Architecture draft. However, I'd agree with @adammontville that our results should (hopefully) "inform any future reincarnation of that draft".

**Comment by slarchacki22** [comment]
Added to FAQ at the 4/25/2022 PACE meeting
