### ISSUE TITLE
How do we want to organize code repositories?

### ISSUE THREAD

**Issue by adammontville** [opencybersecurityalliance/PACE#24]
Because the PACE architecture includes a collection of components, each of which may have separate implementations based on chosen language, we may be better off with multiple PACE code repositories.

At present, PGB needs to be involved to create new repositories. We may want to make the case that code repository creation be delegated, so that the PGB doesn't need to be involved.

**Comment by sparrell** [comment]
The PGB decided at the Feb meeting to delegate repo permission to the TSC and the projects (ie project proposes, TSC approves).

But PACE still needs to decide the process for deciding what 'rates' a OCA PACE repo. One proposal (favored by Duncan) is:
- that any PACE member could propose a new repo, that it be discussed at a Monday meeting, and unless objections it could be created (after TSC approves). 
Another proposal would be come up with a set of entrance criteria that would have to be met (eg project must have been granted LF CII Gold badge) before a project would be considered

We would also need process to decide to archive an repo, particularly if we used the looser first process decided

**Comment by sparrell** [comment]
Ogres (https://github.com/sparrell/Ogres) could be a test case. I would like it to be a PACE repo but it is still in it's nascent form. I favor opening the source while it's still forming so others can contribute. Most projects to date have come in "already baked". How complete does a repo need to be to be considered for becoming a PACE repo?

**Comment by slarchacki22** [comment]
Added to FAQ at the 4/25/2022 PACE meeting
