### ISSUE TITLE
Should pace "pick a winner" for PAR database?

### ISSUE THREAD

**Issue by sparrell** [opencybersecurityalliance/PACE#43]
Should PACE standardize on the database for the PAR or just standardize on the PACE interfaces?

Note this is an independent issue from whether there should be one or more than one reference implementation. For example PACE could decide to allow relational, labeled property graph, or RDF graph databases as long as they met a interface we define; and yet could still decide to have only one reference implementation (eg a Neo4j labeled property graph). Conversely it could decide to standardize on one database (eg a particular Neo4j labeled property graph schema) and still have two different open source PACE repos with different implementations of that database as long as it met the interface standards.

This issue is to decide whether to choose one database (and if so, which one); or to decide to only specify the interfaces.

Possibilities include (and could quibble over which belong in which category):
- Relational databases
   + MySql
   + PostGreSql
   + SqLite
   + MongoDB
   + MariaDB
   + ...
- Graph databases
   + Neo4j
   + OrientDB
   + ArrangoDB
   + DGraph
   + ...
- Ontologies
   + OCA ontology
   + TAC ontology
   + ...
- NoSQL 
   + Cassandra
   + HBase
   + Riak
   + ...

This issue is related to issues #42  and #44

**Comment by sparrell** [comment]
My opinion we should NOT pick a winner. I recommend we specify the interfaces, not implementations. I'd go so far as to recommend we have several reference implementations of different types.

**Comment by davaya** [comment]
As noted at the 3/21 PACE meeting, the items on the list are not peers.  In particular, GraphQL is not  a database, it is an interface style analogous to REST.   REST uses several different HTTP methods (POST, GET, PUT, PATCH, and DELETE) to a bunch of different URLs.  GraphQL uses three actions (query, mutate, delete) to a single URL.

I ran across an article that gives a flavor of the GraphQL approach:  https://medium.com/thundra/better-iot-with-graphql-and-appsync-c3617d5c02d0

**Comment by slarchacki22** [comment]
03/28/2022 - did revisit this issue as we ran out of time previously.  Consensus is to not pick a winner.  Specifying interfaces may weigh in on the implementation.

**Comment by adammontville** [comment]
Is this now resolved?

**Comment by davaya** [comment]
Use case [Retrieve SBOMs](https://github.com/opencybersecurityalliance/PACE/pull/50) suggests retrieving SBOMs through the PES using the Posture Evaluation actuator profile.  This allows both direct retrieval of stored SBOMs and translation of SBOMs from stored format to desired retrieval formats.

An additional use case is to retrieve stored SBOMs directly from the PAR using the unspecified PAR API.  This allows experimentation with candidate APIs without picking a winner at this time, and supports the scalability of direct database access.

**Comment by slarchacki22** [comment]
Added to FAQ at the 4/25/2022 PACE meeting
